#!/usr/bin/with-contenv python

import asyncio
import datetime

async def display_date():
    loop = asyncio.get_running_loop()
    end_time = loop.time() + 5.0
    while True:
        print(datetime.datetime.now())
        if (loop.time() + 1.0) >= end_time:
            break
        await asyncio.sleep(1)

#  asyncio.run(display_date())

async def main(): 
    display = asyncio.create_task(display_date())
    await display

if __name__ == "__main__":    
    asyncio.run(main())
