---
name: HAOS-SBF-MQTT-SensorsGen
version: 2025.9.32
slug: haos-sbf-mqtt-sensorsgen
description: Create your extra sensors for SBFspot multiple inverter setups
url: "https://github.com/habuild/hassio/tree/main/haos-sbfspot"
stage: experimental
image: "ghcr.io/habuild/{arch}-addon-haos-sbf-mqtt-sensorsgen"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
hassio_api: true
panel_icon: mdi:solar-power-variant
boot: manual_only
options:
  InvSerial: "Primary Inverter Serial"
  Plantname: "Primary Inverter Plantname"
  InvSerial2: "Secondary Inverter details"
  Plantname2: ""
  InvName2: ""
  InvSwVer2: "12.35.45"
  InvType2: "model number"
  InvClass2: "Solar Inverter"
  test_msg: false
  Send_Command1: false
  Command1: "/usr/bin/mosquitto_pub -h "{MQTT_Host} -u {MQTT_User} -P {MQTT_Pass} -t homeassistant/sbfspot_{PLANTNAME}/sbfspot_{InvSerial1} -m {"PLANTNAME1","InvSerial1","EToday": "6334"}"
  Send_Command2: false
  Command2: "/usr/bin/mosquitto_pub -h "{MQTT_Host} -u {MQTT_User} -P {MQTT_Pass} -t homeassistant/sbfspot_{PLANTNAME}/sbfspot_{InvSerial2} -m {"PLANTNAME2","InvSerial2","EToday": "9001"}"
  MQTT_User: "!secret mqtt_user"
  MQTT_Pass: "!secret mqtt_pass"
  MQTT_Topic: "homeassistant/sbfspot_{plantname}/sbfspot_{serial}"
  MQTT_Data: >-
    PrgVersion,Plantname,Timestamp,SunRise,SunSet,InvSerial,InvName,InvTime,InvStatus,InvSwVer,InvClass,InvType,InvTemperature,InvGridRelay,EToday,ETotal,GridFreq,PACTot,PAC1,UAC1,IAC1,OperTm,FeedTm,PDCTot,UDC1,UDC2,IDC1,IDC2,PDC1,PDC2,BTSignal,InvWakeupTm,InvSleepTm
  LogLevel: info
schema:
  InvSerial: "str?"
  Plantname: "str?"
  InvSerial2: "str?"
  Plantname2: "str?"
  InvName2: "str?"
  InvSwVer2: "str?"
  InvType2: "str?"
  InvClass2: "str?"
  test_msg: bool
  Send_Command1: bool
  Command1: "str"?
  Send_Command2: bool
  Command2: "str"?
  MQTT_User: "str?"
  MQTT_Pass: "password?"
  MQTT_Topic: "str?"
  MQTT_Data: "str"
  LogLevel: list(debug|info||warning||error)?
