---
name: ETHER-SBFspot
version: dev-104
slug: ether-sbfspot
description: Manage SBFspot with a simple interface
url: "https://github.com/habuild/hassio/tree/main/ether-sbfspot"
stage: experimental
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
homeassistant_api: true
panel_icon: mdi:solar-power-variant

services:
  - mysql:need
  - mqtt:want
options:
  Connection_Type: "Bluetooth"
  Connection:
    - BTAddress: "00:00:00:00:00:00"
    - Password: "0000"
    - LocalBTAddress: "00:00:00:00:00:00"
    - IP_Address: "255:255:255:255"
    - Plantname: MyPlant
    - BTConnectRetries: "10"
  MIS_Enabled: "0"
  Path:
    - OutputPath: "/data/sbfspot/%Y"
    - OutputPathEvents: "/data/sbfspot/%Y/events"
  Location_&_Time:
    - Latitude: "null"
    - Longitude: "null"
    - Timezone: "Europe/Brussels"
    - Locale: "en-US"
    - DateTimeFormat: "%d/%m/%Y %H:%M:%S"
    - DateFormat: "%d/%m/%Y"
    - DecimalPoint: "comma"
    - TimeFormat: "%H:%M:%S"
  Time_Sync:
    - SynchTime: "0"
    - SynchTimeLow: "1"
    - SynchTimeHigh: "3600"
    - SunRSOffset: "900"
    - CalculateMissingSpotValues: "1"
  CSV_Exporting:
    - CSV_Export: "0"
    - CSV_ExtendedHeader: "1"
    - CSV_Header: "1"
    - CSV_SaveZeroPower: "1"
    - CSV_Delimiter: "semicolon"
    - CSV_Spot_TimeSource: "Inverter"
    - CSV_Spot_WebboxHeader: "0"
  Mariadb_SQL:
    - SQL_Database: "null"
    - SQL_Hostname: "core-mariadb"
    - SQL_Port: "3306"
    - SQL_Username: "null"
    - SQL_Password: "null"
  MQTT:
    - MQTT_Publisher: "/usr/bin/mosquitto_pub"
    - MQTT_Host: "core-mosquitto"
    - MQTT_Port: "1883"
    - MQTT_Topic: "homeassistant/sbfspot_{plantname}/sbfspot_{serial}"
    - MQTT_ItemFormat: '"{key}": {value}'
    - MQTT_ItemDelimiter: "comma"
    # yamllint disable-line rule:line-length
    - MQTT_PublisherArgs: -h {host} -u MQTT_Username -P MQTT_Pass -t {topic} -m "{{message}}" -d
    # yamllint disable-line rule:line-length
    - MQTT_Data: Timestamp,SunRise,SunSet,InvSerial,InvName,InvTime,InvStatus,InvTemperature,InvGridRelay,EToday,ETotal,GridFreq,PACTot,UDC1,UDC2,IDC1,IDC2,PDC1,PDC2
    - MQTT_ENABLE: "1"
  PVOutput:
    - PVoutput_SID: "yourSID0123456789:12345"
    - PVoutput_Key: "fake9364fkae4545fake834fake"
    - LogDir: "/data/sbfspot/log/"
    - LogLevel: "info"
schema:
  Connection_Type: list(Bluetooth|Ethernet)?
  Connection:
    - BTAddress: "str?"
    - Password: "str?"
    - LocalBTAddress: "str?"
    - IP_Address: "str?"
    - Plantname: "str"
    - BTConnectRetries: "int"
  MIS_Enabled: "int?"
  Path:
    - OutputPath: "str?"
    - OutputPathEvents: "str?"
  Location_&_Time:
    - Latitude: "float"
    - Longitude: "float"
    - Timezone: "str"
    - Locale: "str"
    - DateTimeFormat: "str"
    - DateFormat: "str"
    - DecimalPoint: "str"
    - TimeFormat: "str"
  Time_Sync:
    - SynchTime: "int"
    - SynchTimeLow: "int"
    - SynchTimeHigh: "int"
    - SunRSOffset: "int"
    - CalculateMissingSpotValues: "int"
  CSV_Exporting:
    - CSV_Export: "int?"
    - CSV_ExtendedHeader: "int?"
    - CSV_Header: "int?"
    - CSV_SaveZeroPower: "int?"
    - CSV_Delimiter: "str?"
    - CSV_Spot_TimeSource: "str?"
    - CSV_Spot_WebboxHeader: "int?"
  Mariadb_SQL:
    - SQL_Database: "str?"
    - SQL_Hostname: "str?"
    - SQL_Port: "str?"
    - SQL_Username: "str?"
    - SQL_Password: "str?"
  MQTT:
    - MQTT_Publisher: "str"
    - MQTT_Host: "str"
    - MQTT_Port: "str"
    - MQTT_Topic: "str"
    - MQTT_ItemFormat: "str"
    - MQTT_ItemDelimiter: str
    - MQTT_PublisherArgs: str
    - MQTT_Data: "str"
    - MQTT_ENABLE: "int"
  PVOutput:
    - PVoutput_SID: "str"
    - PVoutput_Key: "str"
    - LogDir: "str?"
    - LogLevel: "str?"
host_network: true
host_dbus: true
image: "ghcr.io/habuild/{arch}-addon-ether-sbfspot"
